Health:
    prefix: /api/health
    resource: ../src/Health/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false

Album:
    prefix: /api/albums
    resource: ../src/Album/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false
